//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/code/ControlPlay.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlPlay : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlPlay()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlPlay"",
    ""maps"": [
        {
            ""name"": ""Move"",
            ""id"": ""5be7bcbb-8835-4085-93eb-98e07fd103aa"",
            ""actions"": [
                {
                    ""name"": ""GiroIzq"",
                    ""type"": ""Button"",
                    ""id"": ""f3cbe2ff-bad1-43d1-b242-d2e35d449dd3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GiroDer"",
                    ""type"": ""Button"",
                    ""id"": ""ad0d3b5a-4cda-44f5-a3e4-15247b242bfa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mover"",
                    ""type"": ""PassThrough"",
                    ""id"": ""877137f5-bd8e-47d6-a477-c81240d9a107"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Flechas"",
                    ""type"": ""Value"",
                    ""id"": ""8609f03f-f4bc-457c-baa4-3ca372147416"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""506311a0-3fa6-4c03-be92-ce4e23d8e2c3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GiroIzq"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8300f067-1177-47e7-8e12-d9a43956e73f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GiroDer"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bf242dc5-6325-4ab5-8a61-342f8a6c23a7"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mover"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1671976e-f7d3-4e6a-92b9-d8028eb9210a"",
                    ""path"": ""<Gamepad>/dpad"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Flechas"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Move
        m_Move = asset.FindActionMap("Move", throwIfNotFound: true);
        m_Move_GiroIzq = m_Move.FindAction("GiroIzq", throwIfNotFound: true);
        m_Move_GiroDer = m_Move.FindAction("GiroDer", throwIfNotFound: true);
        m_Move_Mover = m_Move.FindAction("Mover", throwIfNotFound: true);
        m_Move_Flechas = m_Move.FindAction("Flechas", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Move
    private readonly InputActionMap m_Move;
    private IMoveActions m_MoveActionsCallbackInterface;
    private readonly InputAction m_Move_GiroIzq;
    private readonly InputAction m_Move_GiroDer;
    private readonly InputAction m_Move_Mover;
    private readonly InputAction m_Move_Flechas;
    public struct MoveActions
    {
        private @ControlPlay m_Wrapper;
        public MoveActions(@ControlPlay wrapper) { m_Wrapper = wrapper; }
        public InputAction @GiroIzq => m_Wrapper.m_Move_GiroIzq;
        public InputAction @GiroDer => m_Wrapper.m_Move_GiroDer;
        public InputAction @Mover => m_Wrapper.m_Move_Mover;
        public InputAction @Flechas => m_Wrapper.m_Move_Flechas;
        public InputActionMap Get() { return m_Wrapper.m_Move; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MoveActions set) { return set.Get(); }
        public void SetCallbacks(IMoveActions instance)
        {
            if (m_Wrapper.m_MoveActionsCallbackInterface != null)
            {
                @GiroIzq.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroIzq;
                @GiroIzq.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroIzq;
                @GiroIzq.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroIzq;
                @GiroDer.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroDer;
                @GiroDer.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroDer;
                @GiroDer.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnGiroDer;
                @Mover.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnMover;
                @Mover.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnMover;
                @Mover.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnMover;
                @Flechas.started -= m_Wrapper.m_MoveActionsCallbackInterface.OnFlechas;
                @Flechas.performed -= m_Wrapper.m_MoveActionsCallbackInterface.OnFlechas;
                @Flechas.canceled -= m_Wrapper.m_MoveActionsCallbackInterface.OnFlechas;
            }
            m_Wrapper.m_MoveActionsCallbackInterface = instance;
            if (instance != null)
            {
                @GiroIzq.started += instance.OnGiroIzq;
                @GiroIzq.performed += instance.OnGiroIzq;
                @GiroIzq.canceled += instance.OnGiroIzq;
                @GiroDer.started += instance.OnGiroDer;
                @GiroDer.performed += instance.OnGiroDer;
                @GiroDer.canceled += instance.OnGiroDer;
                @Mover.started += instance.OnMover;
                @Mover.performed += instance.OnMover;
                @Mover.canceled += instance.OnMover;
                @Flechas.started += instance.OnFlechas;
                @Flechas.performed += instance.OnFlechas;
                @Flechas.canceled += instance.OnFlechas;
            }
        }
    }
    public MoveActions @Move => new MoveActions(this);
    public interface IMoveActions
    {
        void OnGiroIzq(InputAction.CallbackContext context);
        void OnGiroDer(InputAction.CallbackContext context);
        void OnMover(InputAction.CallbackContext context);
        void OnFlechas(InputAction.CallbackContext context);
    }
}
